(() => {
  if (document.querySelector('#barkinder')) return;
  const world = document.querySelector('#world');
  const community = document.querySelector('#community');
  if (!world) return;
  const esc = v => String(v ?? '').replace(/[&<>\'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const style = document.createElement('style');
  style.textContent = `.barkinder{margin-top:14px;background:#fffdf7;border:1px solid var(--line);border-radius:26px;padding:24px;box-shadow:var(--shadow)}.barkinder h3{margin:7px 0 5px;font-size:30px;letter-spacing:-.045em}.barkinder p{color:var(--muted);line-height:1.45}.bk-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.bk-actions button{min-height:42px;padding:10px 14px;border-radius:12px;border:1px solid var(--line);background:#fff;font-weight:900}.bk-actions .bk-primary{background:#191919;color:#fff}.bk-card{margin-top:15px;display:grid;grid-template-columns:100px 1fr;gap:15px;align-items:center;padding:16px;border:1px solid var(--line);border-radius:20px;background:#fff}.bk-avatar{width:100px;height:100px;border-radius:24px;background:#fff3d6;display:grid;place-items:center;font-size:52px}.bk-name{font-size:23px;font-weight:900}.bk-meta{font-size:12px;color:var(--muted);margin-top:3px}.bk-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:9px}.bk-tag{padding:6px 8px;border-radius:999px;background:#f3ecdf;font-size:10px;font-weight:800}.bk-result{margin-top:12px;padding:12px;border-radius:14px;background:#f5eee2;font-size:12px;min-height:18px}.bk-empty{text-align:center;padding:22px;border:1px dashed var(--line);border-radius:16px;color:var(--muted)}@media(max-width:720px){.bk-card{grid-template-columns:70px 1fr}.bk-avatar{width:70px;height:70px;font-size:38px}.barkinder h3{font-size:25px}}`;
  document.head.appendChild(style);
  const card = document.createElement('section'); card.id='barkinder'; card.className='barkinder';
  card.innerHTML = `<span class="tag">BARKINDER · DOG SOCIAL</span><h3>Find a friend for your dog</h3><p>A playful Tinder-style discovery experience using dogs already registered in the BARKVERSE community. No private phone numbers, emails or exact locations are exposed.</p><div class="bk-actions"><button id="bkDiscover" class="bk-primary" type="button">🐾 Discover dogs</button><button id="bkRefresh" type="button">↻ Refresh</button></div><div id="bkCard" class="bk-card"><div class="bk-empty" style="grid-column:1/-1">Tap Discover to find registered dogs.</div></div><div id="bkActions" class="bk-actions" hidden><button id="bkPass" type="button">✕ Pass</button><button id="bkLike" class="bk-primary" type="button">♥ Like</button><button id="bkPlay" type="button">🎾 Play</button></div><div id="bkResult" class="bk-result">BARKINDER only uses community profiles returned by BARKVERSE.</div>`;
  if (community) world.insertBefore(card, community); else world.appendChild(card);
  const ui={card:card.querySelector('#bkCard'),actions:card.querySelector('#bkActions'),result:card.querySelector('#bkResult')};
  let members=[], index=0;
  const currentAccount=()=>window.BARKVERSE_COMMUNITY?.getAccount?.() || null;
  const currentDog=()=>window.BARKVERSE_DOG || {name:document.querySelector('#dogName')?.textContent||'Your Dog'};
  const emoji=m=>{const b=String(m.breed||'').toLowerCase();if(/husky|shepherd/.test(b))return '🐺';if(/poodle|shih|maltese/.test(b))return '🐩';if(/retriever|lab/.test(b))return '🦮';if(/pug|bulldog/.test(b))return '🐕';return '🐶'};
  async function load(){ui.result.textContent='Loading registered dogs…';try{const r=await fetch('/api/community?action=list');const d=await r.json();members=(d.members||[]).filter(m=>m.accountId!==currentAccount()?.accountId && !m.demo);if(!members.length && d.mode==='local')members=(d.members||[]).filter(m=>m.accountId!==currentAccount()?.accountId);index=0;show();}catch{members=[];show();ui.result.textContent='Dog community is temporarily unavailable.';}}
  function show(){const m=members[index];if(!m){ui.card.innerHTML='<div class="bk-empty" style="grid-column:1/-1">No other registered dogs are available right now. More dogs appear as their humans join BARKVERSE.</div>';ui.actions.hidden=true;return}ui.card.innerHTML=`<div class="bk-avatar">${emoji(m)}</div><div><div class="bk-name">${esc(m.dogName||'Your Dog')}</div><div class="bk-meta">${esc(m.breed||'Mixed breed')} · ${esc(m.status||'online')}</div><div class="bk-tags">${(m.traits||[]).slice(0,4).map(t=>`<span class="bk-tag">${esc(t)}</span>`).join('')}</div></div>`;ui.actions.hidden=false;ui.result.textContent=`Dog ${index+1} of ${members.length} · registered BARKVERSE profile`}
  async function event(action){const target=members[index];if(!target)return;const me=currentDog();const account=currentAccount();if(!account){ui.result.textContent='Join the BARKVERSE community first, then you can connect with other registered dogs.';return}try{await fetch('/api/community?action=event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accountId:account.accountId,targetId:target.accountId,eventAction:action})})}catch{}if(action==='like'){ui.result.textContent=`♥ ${me.name||'Your Dog'} liked ${target.dogName||'this dog'}. If they like back, BARKINDER can become a match.`}else if(action==='play'){ui.result.textContent=`🎾 ${me.name||'Your Dog'} sent a play invitation to ${target.dogName||'the other dog'}.`}else{ui.result.textContent=`${target.dogName||'Dog'} passed for now.`}index++;show()}
  card.querySelector('#bkDiscover').addEventListener('click',load);card.querySelector('#bkRefresh').addEventListener('click',load);card.querySelector('#bkPass').addEventListener('click',()=>event('pass'));card.querySelector('#bkLike').addEventListener('click',()=>event('like'));card.querySelector('#bkPlay').addEventListener('click',()=>event('play'));
  window.BARKVERSE_BARKINDER={refresh:load};
})();
