(() => {
  'use strict';
  const KEY = 'barkverse.experience.v1';
  const LANGS = {
    en:{name:'English',voice:'en-US',welcome:'Welcome to the dog world',next:'Next',back:'Back',skip:'Skip tour',done:'Start exploring',country:'Country',language:'Language',faq:'FAQ',help:'How can I help?',placeholder:'Ask me how BARKVERSE works…',thanks:'Thank you for visiting BARKVERSE. Come back anytime.',steps:[['1 · Meet your dog','Start by taking a photo or choosing one from your gallery. BARKVERSE checks that it is really a dog.'],['2 · Discover','AI creates your dog profile, breed estimate, mood, traits and a playful identity.'],['3 · Explore','Investigate the case, play Barkcade, talk to your dog, create a memory and explore the Observatory.'],['4 · Connect','Join the community and discover registered dogs in BARKINDER. Like, pass or invite a dog to play.'],['5 · Make it yours','Use Dog Passport, privacy controls, language settings and the floating help bot whenever you need them.']]},
    hi:{name:'हिन्दी',voice:'hi-IN',welcome:'डॉग वर्ल्ड में आपका स्वागत है',next:'आगे',back:'पीछे',skip:'टूर छोड़ें',done:'शुरू करें',country:'देश',language:'भाषा',faq:'सामान्य सवाल',help:'मैं कैसे मदद करूँ?',placeholder:'पूछें कि BARKVERSE कैसे काम करता है…',thanks:'BARKVERSE पर आने के लिए धन्यवाद। फिर मिलेंगे।',steps:[['1 · अपने डॉग से मिलें','कैमरा से फोटो लें या गैलरी से फोटो चुनें। BARKVERSE पहले जांचेगा कि फोटो में वास्तव में डॉग है।'],['2 · खोजें','AI आपके डॉग का प्रोफाइल, नस्ल का अनुमान, मूड, traits और मजेदार identity बनाएगा।'],['3 · एक्सप्लोर करें','केस investigate करें, Barkcade खेलें, डॉग से बात करें, memory बनाएं और Observatory देखें।'],['4 · कनेक्ट करें','Community में शामिल हों और BARKINDER में registered dogs खोजें। Like, Pass या Play करें।'],['5 · अपना अनुभव बनाएं','Dog Passport, privacy, language और floating help bot का इस्तेमाल कभी भी करें।']]},
    es:{name:'Español',voice:'es-ES',welcome:'Bienvenido al mundo de los perros',next:'Siguiente',back:'Atrás',skip:'Saltar tour',done:'Empezar',country:'País',language:'Idioma',faq:'Preguntas frecuentes',help:'¿Cómo puedo ayudarte?',placeholder:'Pregúntame cómo funciona BARKVERSE…',thanks:'Gracias por visitar BARKVERSE. ¡Vuelve cuando quieras!',steps:[['1 · Conoce a tu perro','Toma una foto o elige una de tu galería. BARKVERSE comprueba que sea realmente un perro.'],['2 · Descubre','La IA crea su perfil, estimación de raza, estado de ánimo y personalidad.'],['3 · Explora','Investiga el caso, juega Barkcade, habla con tu perro, crea un recuerdo y mira el Observatory.'],['4 · Conecta','Únete a la comunidad y descubre perros registrados en BARKINDER.'],['5 · Personaliza','Usa Dog Passport, privacidad, idiomas y el bot de ayuda cuando quieras.']]},
    fr:{name:'Français',voice:'fr-FR',welcome:'Bienvenue dans le monde des chiens',next:'Suivant',back:'Retour',skip:'Passer le tour',done:'Commencer',country:'Pays',language:'Langue',faq:'FAQ',help:'Comment puis-je aider ?',placeholder:'Demandez-moi comment fonctionne BARKVERSE…',thanks:'Merci de votre visite sur BARKVERSE. À bientôt !',steps:[['1 · Rencontrez votre chien','Prenez une photo ou choisissez-en une dans votre galerie. BARKVERSE vérifie que c’est bien un chien.'],['2 · Découvrez','L’IA crée son profil, son estimation de race, son humeur et ses traits.'],['3 · Explorez','Enquêtez, jouez à Barkcade, parlez à votre chien, créez un souvenir et consultez l’Observatory.'],['4 · Connectez-vous','Rejoignez la communauté et découvrez les chiens inscrits sur BARKINDER.'],['5 · Personnalisez','Utilisez Dog Passport, la confidentialité, les langues et le bot d’aide.']]},
    de:{name:'Deutsch',voice:'de-DE',welcome:'Willkommen in der Hundewelt',next:'Weiter',back:'Zurück',skip:'Tour überspringen',done:'Starten',country:'Land',language:'Sprache',faq:'FAQ',help:'Wie kann ich helfen?',placeholder:'Frage mich, wie BARKVERSE funktioniert…',thanks:'Danke für deinen Besuch bei BARKVERSE. Bis bald!',steps:[['1 · Deinen Hund treffen','Mach ein Foto oder wähle eines aus der Galerie. BARKVERSE prüft, ob es wirklich ein Hund ist.'],['2 · Entdecken','Die KI erstellt Profil, Rasseschätzung, Stimmung und Eigenschaften.'],['3 · Erkunden','Löse den Fall, spiele Barkcade, sprich mit deinem Hund, erstelle eine Erinnerung und öffne das Observatory.'],['4 · Verbinden','Tritt der Community bei und entdecke registrierte Hunde in BARKINDER.'],['5 · Anpassen','Nutze Dog Passport, Datenschutz, Sprachen und den Hilfe-Bot.']]},
    ja:{name:'日本語',voice:'ja-JP',welcome:'犬の世界へようこそ',next:'次へ',back:'戻る',skip:'ツアーをスキップ',done:'始める',country:'国',language:'言語',faq:'よくある質問',help:'どうお手伝いしましょう？',placeholder:'BARKVERSEの使い方を聞いてください…',thanks:'BARKVERSEをご利用いただきありがとうございます。また遊びに来てください。',steps:[['1 · 愛犬に会う','カメラで撮影するか、ギャラリーから写真を選びます。BARKVERSEが犬の写真か確認します。'],['2 · 発見する','AIがプロフィール、犬種推定、気分、特徴を作ります。'],['3 · 探索する','事件を調査し、Barkcadeで遊び、犬と話し、思い出を作り、Observatoryを見ます。'],['4 · つながる','コミュニティに参加してBARKINDERで登録済みの犬を探します。'],['5 · 自分らしく','Dog Passport、プライバシー、言語、ヘルプボットを使えます。']]},
    ko:{name:'한국어',voice:'ko-KR',welcome:'강아지 세계에 오신 것을 환영합니다',next:'다음',back:'이전',skip:'투어 건너뛰기',done:'시작하기',country:'국가',language:'언어',faq:'자주 묻는 질문',help:'무엇을 도와드릴까요?',placeholder:'BARKVERSE 사용법을 물어보세요…',thanks:'BARKVERSE를 방문해 주셔서 감사합니다. 또 만나요!',steps:[['1 · 강아지 만나기','카메라로 찍거나 갤러리에서 사진을 선택하세요. BARKVERSE가 강아지 사진인지 확인합니다.'],['2 · 발견하기','AI가 프로필, 품종 추정, 기분과 특성을 만듭니다.'],['3 · 탐험하기','사건을 조사하고 Barkcade를 플레이하고 강아지와 대화하고 추억을 만드세요.'],['4 · 연결하기','커뮤니티에 참여하고 BARKINDER에서 등록된 강아지를 만나세요.'],['5 · 나만의 경험','Dog Passport, 개인정보, 언어와 도움말 봇을 이용하세요.']]}
  };
  const COUNTRIES = [['IN','India','hi'],['US','United States','en'],['GB','United Kingdom','en'],['ES','Spain','es'],['FR','France','fr'],['DE','Germany','de'],['JP','Japan','ja'],['KR','South Korea','ko']];
  let saved; try { saved = JSON.parse(localStorage.getItem(KEY)||'null') || {}; } catch { saved={}; }
  let lang = LANGS[saved.lang] ? saved.lang : 'en';
  const t=()=>LANGS[lang];
  const style=document.createElement('style'); style.textContent=`.bv-lang{position:fixed;top:12px;right:12px;z-index:10001;display:flex;gap:6px;background:#fffdf7eF;border:1px solid var(--line);border-radius:999px;padding:5px;box-shadow:0 10px 30px #0002;backdrop-filter:blur(12px)}.bv-lang select{border:0;background:transparent;font:900 11px inherit;outline:0;padding:7px}.bv-overlay{position:fixed;inset:0;z-index:10000;background:#171717b8;display:grid;place-items:center;padding:18px;backdrop-filter:blur(8px)}.bv-tour{width:min(620px,100%);background:#fffdf7;border-radius:28px;padding:25px;box-shadow:0 30px 90px #0005}.bv-progress{height:6px;background:#eee8dc;border-radius:9px;overflow:hidden;margin:14px 0}.bv-progress i{display:block;height:100%;background:var(--accent);transition:width .35s}.bv-tour h2{font-size:30px;margin:8px 0}.bv-tour p{color:var(--muted);line-height:1.55}.bv-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin-top:20px}.bv-actions button,.bv-tour select{border:1px solid var(--line);border-radius:12px;padding:11px 14px;background:#fff;font-weight:900}.bv-actions .primary{background:#191919;color:#fff}.bv-status{position:fixed;left:50%;bottom:20px;transform:translate(-50%,20px);opacity:0;z-index:10005;max-width:min(92vw,560px);padding:13px 16px;border-radius:15px;background:#191919;color:#fff;font-size:12px;font-weight:800;box-shadow:0 15px 40px #0004;transition:.25s;pointer-events:none}.bv-status.show{opacity:1;transform:translate(-50%,0)}.bv-status.ok{background:#267641}.bv-status.bad{background:#9f3030}.bv-faq{margin:18px 0;background:#fffdf7;border:1px solid var(--line);border-radius:24px;padding:22px}.bv-faq details{border-top:1px solid var(--line);padding:12px 0}.bv-faq summary{cursor:pointer;font-weight:900}.bv-faq p{color:var(--muted);line-height:1.5}.bv-bot{position:fixed;right:16px;bottom:62px;z-index:10004}.bv-bot-btn{width:54px;height:54px;border:0;border-radius:50%;background:#191919;color:#fff;font-size:23px;box-shadow:0 14px 35px #0003}.bv-chat{position:absolute;right:0;bottom:64px;width:min(340px,calc(100vw - 32px));background:#fffdf7;border:1px solid var(--line);border-radius:20px;box-shadow:0 20px 60px #0004;padding:14px;display:none}.bv-chat.open{display:block}.bv-chat h4{margin:0 0 8px}.bv-chat-msg{min-height:90px;color:var(--muted);font-size:12px;line-height:1.5}.bv-chat-row{display:flex;gap:6px}.bv-chat-row input{flex:1;min-width:0;border:1px solid var(--line);border-radius:10px;padding:9px}.bv-chat-row button{border:0;border-radius:10px;background:#191919;color:#fff;padding:9px 12px}.bv-faq-search{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;margin:8px 0 12px}@media(max-width:720px){.bv-lang{top:8px;right:8px}.bv-tour{padding:20px}.bv-tour h2{font-size:25px}.bv-bot{right:12px;bottom:60px}}`; document.head.appendChild(style);
  const status=(msg,type='')=>{let el=document.querySelector('.bv-status');if(!el){el=document.createElement('div');el.className='bv-status';document.body.appendChild(el)}el.textContent=msg;el.className=`bv-status show ${type}`;clearTimeout(status.timer);status.timer=setTimeout(()=>el.classList.remove('show'),3000)};
  function save(){localStorage.setItem(KEY,JSON.stringify({...saved,lang,country:saved.country||''}))}
  function languageBar(){const bar=document.createElement('div');bar.className='bv-lang';bar.innerHTML=`<select aria-label="${t().language}">${Object.entries(LANGS).map(([k,v])=>`<option value="${k}" ${k===lang?'selected':''}>${v.name}</option>`).join('')}</select>`;bar.querySelector('select').onchange=e=>setLanguage(e.target.value);document.body.appendChild(bar)}
  function setLanguage(next){if(!LANGS[next])return;lang=next;save();translateStatic();status(`${t().language}: ${t().name}`,'ok');if(document.querySelector('.bv-overlay'))renderTour();if(document.querySelector('.bv-chat.open'))renderBot();}
  function translateStatic(){const map={ '#demoBtn':t().done,'#caseBtn':t().next,'#barkcadeStart':t().next,'#talkBtn':t().next,'#memoryBtn':t().next,'#observatoryBtn':t().next,'#editDogBtn':t().next,'#dogNameInput':t().name==='हिन्दी'?'डॉग का नाम (वैकल्पिक)':'Dog name (optional)','#talkInput':t().placeholder};Object.entries(map).forEach(([s,v])=>{const e=document.querySelector(s);if(e&&e.tagName==='BUTTON')e.textContent=v;else if(e)e.placeholder=v});}
  function renderTour(step=0){let overlay=document.querySelector('.bv-overlay');if(!overlay){overlay=document.createElement('div');overlay.className='bv-overlay';document.body.appendChild(overlay)}const steps=t().steps;const s=Math.max(0,Math.min(step,steps.length-1));overlay.innerHTML=`<div class="bv-tour"><small>${t().welcome}</small><div class="bv-progress"><i style="width:${((s+1)/steps.length)*100}%"></i></div><h2>${steps[s][0]}</h2><p>${steps[s][1]}</p><div class="bv-actions"><button data-skip>${t().skip}</button>${s>0?`<button data-back>${t().back}</button>`:''}<button class="primary" data-next>${s===steps.length-1?t().done:t().next}</button></div></div>`;overlay.querySelector('[data-skip]').onclick=()=>finishTour();overlay.querySelector('[data-back]')?.addEventListener('click',()=>renderTour(s-1));overlay.querySelector('[data-next]').onclick=()=>s===steps.length-1?finishTour():renderTour(s+1)}
  function finishTour(){document.querySelector('.bv-overlay')?.remove();saved.seen=true;save();status(t().welcome+' · '+t().done,'ok');}
  function addFaq(){const world=document.querySelector('#world');if(!world||document.querySelector('#bvFaq'))return;const sec=document.createElement('section');sec.id='bvFaq';sec.className='bv-faq card';const q=lang==='hi'?[['BARKVERSE कैसे शुरू करें?','पहले डॉग की clear photo लें या gallery से upload करें। केवल dog photos स्वीकार होती हैं।'],['गलत photo डालने पर क्या होगा?','AI photo को check करेगा और dog नहीं होने पर तुरंत reject करेगा।'],['BARKINDER क्या है?','यह registered BARKVERSE dogs के लिए playful discovery और interaction space है।'],['क्या photo blockchain पर जाती है?','नहीं। private dog photos blockchain पर नहीं लिखी जातीं।'],['भाषा बदलने पर audio भी बदलेगा?','हाँ। selected language voice requests और browser voice fallback दोनों में इस्तेमाल होती है।']]:[['How do I start BARKVERSE?','Take a clear dog photo or choose one from your gallery. Only dog photos are accepted.'],['What happens to a wrong photo?','The AI gatekeeper checks it and rejects images that are not clearly dogs.'],['What is BARKINDER?','A playful discovery and interaction space for registered BARKVERSE dogs.'],['Are photos written to blockchain?','No. Private dog photos are not written to the blockchain.'],['Does changing language change audio?','Yes. The selected language is carried into voice requests and browser voice fallback.']];sec.innerHTML=`<span class="tag">${t().faq}</span><h3>${t().faq}</h3><input class="bv-faq-search" placeholder="${t().placeholder}">${q.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}`;world.appendChild(sec);}
  function renderBot(){let wrap=document.querySelector('.bv-bot');if(!wrap){wrap=document.createElement('div');wrap.className='bv-bot';document.body.appendChild(wrap)}wrap.innerHTML=`<div class="bv-chat"><h4>🐾 ${t().help}</h4><div class="bv-chat-msg">${t().welcome}. ${t().steps[0][1]}</div><div class="bv-chat-row"><input placeholder="${t().placeholder}"><button>→</button></div></div><button class="bv-bot-btn" aria-label="${t().help}">🐾</button>`;const chat=wrap.querySelector('.bv-chat'),btn=wrap.querySelector('.bv-bot-btn'),input=wrap.querySelector('input'),out=wrap.querySelector('.bv-chat-msg');btn.onclick=()=>chat.classList.toggle('open');wrap.querySelector('button:not(.bv-bot-btn)').onclick=()=>{const q=input.value.toLowerCase();let a=t().steps.find(s=>q.includes(s[0].split('·')[1]?.trim().toLowerCase().slice(0,8)))?.[1];if(!a){if(/photo|upload|camera|फोटो|अपलोड/.test(q))a=t().steps[0][1];else if(/barkinder|match|like|dog/.test(q))a=t().steps[3][1];else if(/talk|voice|audio|आवाज|बोल/.test(q))a=t().steps[2][1];else a=t().steps[4][1]}out.textContent=a;input.value='';};}
  function operationFeedback(){const original=window.fetch.bind(window);window.fetch=async(url,opts={})=>{const isApi=String(url).startsWith('/api/');if(isApi)status(lang==='hi'?'काम चल रहा है…':'Working…');try{const res=await original(url,opts);if(isApi){if(res.ok)status(lang==='hi'?'सफल · काम पूरा हुआ':'Success · done','ok');else status(lang==='hi'?'यह काम पूरा नहीं हो सका':'That action could not be completed','bad')}return res}catch(e){if(isApi)status(lang==='hi'?'कनेक्शन में समस्या हुई':'Connection problem','bad');throw e}};}
  // Keep browser speech in the selected language, including when ElevenLabs is unavailable.
  const patchSpeech=()=>{if(!window.speechSynthesis||window.__bvSpeechPatched)return;const original=window.speechSynthesis.speak.bind(window.speechSynthesis);window.speechSynthesis.speak=(u)=>{try{u.lang=t().voice}catch{}return original(u)};window.__bvSpeechPatched=true};
  function init(){languageBar();translateStatic();renderBot();addFaq();operationFeedback();patchSpeech();if(!saved.seen)renderTour();window.addEventListener('beforeunload',()=>{try{navigator.sendBeacon('/api/community?action=leave',JSON.stringify({accountId:window.BARKVERSE_COMMUNITY?.getAccount?.()?.accountId}))}catch{}});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.BARKVERSE_EXPERIENCE={getLanguage:()=>lang,setLanguage,showTour:()=>renderTour(0),status,translations:LANGS};
})();
