(()=>{
const root=document.querySelector('#world');if(!root)return;
const KEY='barkverse.life.v1';const life=JSON.parse(localStorage.getItem(KEY)||'{"paw":0,"last":"","streak":0}');
const dogs=[['milo','Milo','Snack Engineer','🐕',14,58],['luna','Luna','Moonlight Detective','🐺',72,30],['biscuit','Biscuit','Treat Accountant','🐶',42,67],['pepper','Pepper','Ball Scientist','🐕‍🦺',83,67],['coco','Coco','Professional Napper','🐩',25,25]];
const scenes=[['The Ball Nobody Could Catch','Milo lost the tennis ball. Luna saw it roll behind the fountain.','Find the ball','Milo: “I absolutely meant to drop it there.” Luna: “Sure you did.”'],['Treat Diplomacy','Biscuit has one biscuit and four friends. A summit has begun.','Negotiate treats','Biscuit: “We can discuss this calmly. From a safe distance.”'],['The Suspicious Puddle','Pepper found a puddle shaped suspiciously like a pawprint.','Investigate puddle','Pepper: “Evidence!” Coco: “That is water.” Pepper: “Suspicious water.”'],['Zoomie Weather Alert','The park entered a high-zoomie weather system. Humans should hold their hats.','Start zoomies','Luna: “Ready?” Milo: “I was born ready.”'],['The Quiet Bench Mystery','Coco found a lonely ball beside the old bench.','Follow the pawprints','Coco: “This story needs a happy ending.”']];
let scene=Math.floor(Date.now()/18000)%scenes.length,paused=false,ctx=null,music=true;
const css=document.createElement('style');css.textContent=`.living-world{margin:18px 0;padding:18px;border:1px solid var(--line);border-radius:28px;background:linear-gradient(#e7f7ff,#f5efd9);min-height:390px;position:relative;overflow:hidden}.living-head{display:flex;justify-content:space-between;gap:12px}.living-head h3{margin:6px 0;font-size:25px}.living-head p{margin:0;color:var(--muted);font-size:11px;line-height:1.4}.life-controls{display:flex;gap:6px;flex-wrap:wrap}.life-controls button,.park-task button{border:1px solid #d7cbb8;background:#fffdf7;border-radius:11px;padding:9px 11px;font-size:9px;font-weight:900}.park{position:absolute;left:14px;right:14px;top:120px;bottom:15px;border-radius:21px;overflow:hidden;background:linear-gradient(#b9e5ff 0 43%,#b6d887 43%)}.park:after{content:'☀️';position:absolute;right:8%;top:8%;font-size:45px}.tree{position:absolute;bottom:16%;font-size:55px}.t1{left:5%}.t2{right:5%}.pond{position:absolute;left:37%;bottom:8%;width:27%;height:35px;border-radius:50%;background:#76cde0aa}.park-dog{position:absolute;z-index:4;border:0;background:none;display:flex;flex-direction:column;align-items:center;transition:left 1.6s ease,top 1.6s ease;cursor:pointer}.park-dog .face{font-size:38px;animation:dogbob 1.7s ease-in-out infinite}.park-dog small{font-size:8px;font-weight:900;background:#fffdf7e8;border-radius:99px;padding:4px 7px;white-space:nowrap}.bubble{position:absolute;bottom:62px;background:#fff;border:2px solid #191919;border-radius:13px;padding:7px;min-width:130px;font-size:9px;font-weight:800;opacity:0;transition:.25s;pointer-events:none}.bubble.show{opacity:1}.park-task{position:absolute;z-index:8;left:15px;right:15px;bottom:12px;background:#191919eF;color:#fff;border-radius:14px;padding:10px;display:flex;align-items:center;justify-content:space-between;gap:8px}.park-task b{font-size:10px}.park-task span{display:block;color:#ddd;font-size:8px;margin-top:2px}.park-task button{background:#fff;color:#191919;border:0}.life-log{margin-top:10px;padding:12px;border:1px solid var(--line);border-radius:15px;background:#fffdf8}.life-log b{font-size:11px}.life-log p{margin:5px 0;color:var(--muted);font-size:10px}.life-reward{display:flex;gap:7px;flex-wrap:wrap}.life-reward span{padding:6px 9px;border-radius:99px;background:#fff1bc;font-size:9px;font-weight:900}.music-note{font-size:9px;color:var(--muted);margin-top:7px}@keyframes dogbob{0%,100%{transform:translateY(0) rotate(-2deg)}50%{transform:translateY(-5px) rotate(2deg)}}@media(max-width:720px){.living-world{min-height:440px;padding:14px}.living-head{display:block}.life-controls{margin-top:8px}.park{top:145px}.park-dog .face{font-size:31px}}@media(prefers-reduced-motion:reduce){.park-dog,.face{animation:none!important;transition:none!important}}`;document.head.appendChild(css);
const box=document.createElement('section');box.className='living-world';box.innerHTML=`<div class="living-head"><div><span class="tag">🐾 BARK PARK · LIVE STORY</span><h3>The park has a mission.</h3><p>Dogs have jobs, clues, arguments and tiny adventures. Your human gets to join them.</p></div><div class="life-controls"><button id="lifeMusic">🎵 Music On</button><button id="lifeNext">📖 Next scene</button><button id="lifePause">⏸ Pause</button></div></div><div class="park" id="park"><div class="tree t1">🌳</div><div class="tree t2">🌲</div><div class="pond"></div><div id="parkDogs"></div><div class="park-task"><div><b id="taskTitle"></b><span id="taskText"></span></div><button id="taskBtn">Do it →</button></div></div>`;root.insertBefore(box,root.querySelector('.grid'));
const log=document.createElement('div');log.className='life-log';log.innerHTML='<b id="lifeTitle"></b><p id="lifeLine"></p><div class="life-reward"><span id="paw">🐾 0 Pawprints</span><span id="daily">☀️ Daily mission ready</span></div><div class="music-note">🎵 Cozy original background tones are generated locally in your browser.</div>';box.after(log);
const $=s=>document.querySelector(s);const park=$('#parkDogs'),title=$('#lifeTitle'),line=$('#lifeLine'),taskTitle=$('#taskTitle'),taskText=$('#taskText'),paw=$('#paw'),daily=$('#daily');
function save(){localStorage.setItem(KEY,JSON.stringify(life))}function today(){return new Date().toISOString().slice(0,10)}
function chime(){try{if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=523;o.type='sine';g.gain.value=.04;o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.22)}catch{}}
function bark(){try{if(typeof window.BARKVERSE_BARK==='function')window.BARKVERSE_BARK('happy')}catch{}}
function speak(d,t){const b=d.querySelector('.bubble');b.textContent=t;b.classList.add('show');setTimeout(()=>b.classList.remove('show'),3500)}
function render(){const s=scenes[scene];title.textContent=`Chapter ${scene+1} · ${s[0]}`;line.textContent=s[3];taskTitle.textContent=s[0];taskText.textContent=s[1];paw.textContent=`🐾 ${life.paw||0} Pawprints`;daily.textContent=life.last===today()?'✓ Daily mission complete':'☀️ Daily mission ready';dogs.forEach((d,i)=>{const el=document.getElementById('pd-'+d[0]);if(!el)return;let x=d[4],y=d[5];if(i===scene%dogs.length){x=38+(scene*11)%34;y=28+(scene*13)%43}if(i===(scene+1)%dogs.length){x+=7;y+=4}el.style.left=Math.min(88,Math.max(4,x))+'%';el.style.top=Math.min(72,Math.max(7,y))+'%'});}
dogs.forEach(d=>{const el=document.createElement('button');el.type='button';el.id='pd-'+d[0];el.className='park-dog';el.style.left=d[4]+'%';el.style.top=d[5]+'%';el.innerHTML=`<span class="bubble"></span><span class="face">${d[3]}</span><small>${d[1]} · ${d[2]}</small>`;el.addEventListener('click',()=>{speak(el,`${d[1]}: “${d[2]} reporting for duty. Want to play?”`);bark();chime()});park.appendChild(el)});
function next(){scene=(scene+1)%scenes.length;render();const a=document.getElementById('pd-'+dogs[scene%dogs.length][0]),b=document.getElementById('pd-'+dogs[(scene+2)%dogs.length][0]);setTimeout(()=>speak(a,scenes[scene][3]),400);setTimeout(()=>speak(b,'“I have a better plan.”'),1500);bark();chime()}
$('#taskBtn').onclick=()=>{life.paw=(life.paw||0)+3;life.last=today();life.streak=(life.streak||0)+1;save();render();const a=document.getElementById('pd-'+dogs[scene%dogs.length][0]),b=document.getElementById('pd-'+dogs[(scene+1)%dogs.length][0]);speak(a,'Mission complete! High five, human!');setTimeout(()=>speak(b,'“Three pawprints. I approve.”'),900);bark();chime()};$('#lifeNext').onclick=next;$('#lifePause').onclick=e=>{paused=!paused;e.target.textContent=paused?'▶ Resume':'⏸ Pause'};
function music(){try{ctx=new(window.AudioContext||window.webkitAudioContext)();const gain=ctx.createGain();gain.gain.value=.012;gain.connect(ctx.destination);const notes=[261.6,329.6,392,329.6,293.7,392];let i=0;setInterval(()=>{if(!music||paused)return;const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=notes[i++%notes.length];g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.linearRampToValueAtTime(.3,ctx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.5);o.connect(g);g.connect(gain);o.start();o.stop(ctx.currentTime+.52)},650)}catch{}}
$('#lifeMusic').onclick=e=>{music=!music;e.target.textContent=music?'🎵 Music On':'🔇 Music Off';if(music&&!ctx)music()};document.addEventListener('visibilitychange',()=>{if(document.hidden&&ctx)ctx.suspend()});
render();music();setInterval(()=>{if(!paused){next()}},18000);window.BARKVERSE_LIFE={next,complete:()=>$('#taskBtn').click(),paw:()=>life.paw||0};
})();
