(() => {
  const world = document.querySelector('#world');
  if (!world || document.querySelector('#livingDogPark')) return;

  const reduced = window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches;
  const KEY = 'barkverse.daily.v1';
  const read = () => { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } };
  const save = (v) => { try { localStorage.setItem(KEY, JSON.stringify(v)); } catch {} };
  const dayKey = () => new Date().toISOString().slice(0, 10);
  const esc = (v) => String(v ?? '').replace(/[&<>\'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

  const style = document.createElement('style');
  style.textContent = `
    .living-card{margin-top:16px;background:#fffdf7;border:1px solid var(--line);border-radius:26px;padding:22px;box-shadow:var(--shadow);overflow:hidden}
    .living-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.living-head h3{margin:7px 0 5px;font-size:30px;letter-spacing:-.045em}.living-head p{margin:0;color:var(--muted);line-height:1.5;max-width:720px}.live-pill{display:inline-flex;align-items:center;gap:7px;padding:8px 11px;border-radius:999px;background:#e9f8ed;color:#267641;font-size:10px;font-weight:900;white-space:nowrap}.live-pill i{width:7px;height:7px;border-radius:50%;background:var(--good);animation:ambientPulse 1.4s ease-in-out infinite}
    .park-stage{position:relative;height:330px;margin-top:17px;border:1px solid #e8dfcf;border-radius:23px;overflow:hidden;background:linear-gradient(#dff4ff 0 43%,#bfe6a9 43% 100%);isolation:isolate}.park-stage:before{content:"☁️     ☁️                         ☁️";position:absolute;inset:22px 0 auto 0;text-align:center;font-size:26px;letter-spacing:45px;opacity:.45;z-index:-1}.park-sun{position:absolute;right:25px;top:18px;font-size:40px}.park-path{position:absolute;left:-8%;right:-8%;bottom:12px;height:115px;border-radius:50%;background:#ead4a5;transform:rotate(-3deg);box-shadow:inset 0 0 0 14px #d6bd8a}.park-tree{position:absolute;bottom:74px;font-size:48px;filter:drop-shadow(0 8px 5px #0001)}.park-tree.t1{left:4%}.park-tree.t2{right:5%}.park-water{position:absolute;right:24%;bottom:28px;width:150px;height:48px;border-radius:50%;background:#8dd9edaa;border:2px solid #6fc6dd}
    .park-dog{position:absolute;z-index:3;font-size:42px;line-height:1;filter:drop-shadow(0 7px 5px #0002);cursor:pointer;user-select:none;transform-origin:50% 80%;transition:filter .2s}.park-dog:hover{filter:drop-shadow(0 9px 8px #0003) brightness(1.06)}.park-dog small{position:absolute;left:50%;bottom:100%;transform:translateX(-50%);padding:4px 7px;border-radius:9px;background:#fff;color:#191919;border:1px solid var(--line);font-size:9px;font-weight:900;white-space:nowrap;opacity:0;pointer-events:none;transition:opacity .2s}.park-dog:hover small,.park-dog:focus small{opacity:1}.park-dog.d1{left:8%;bottom:68px;animation:parkRunA 7s ease-in-out infinite}.park-dog.d2{left:42%;bottom:86px;animation:parkRunB 8s ease-in-out infinite}.park-dog.d3{left:69%;bottom:58px;animation:parkRunC 9s ease-in-out infinite}.park-dog.d4{left:25%;bottom:42px;animation:parkRunD 10s ease-in-out infinite}.park-dog.d5{left:82%;bottom:115px;animation:parkRunE 8.5s ease-in-out infinite}.park-dog.playing{animation:dogPlay .9s ease-in-out 2!important}.park-ball{position:absolute;z-index:4;font-size:20px;opacity:0;pointer-events:none}.park-ball.fly{animation:ballFly 1.4s ease-out forwards}.park-heart{position:absolute;z-index:5;font-size:20px;opacity:0;pointer-events:none}.park-heart.pop{animation:heartPop 1.3s ease-out forwards}
    .living-bottom{display:grid;grid-template-columns:1.35fr .65fr;gap:12px;margin-top:12px}.story-box,.daily-box{border:1px solid var(--line);border-radius:19px;background:#fff;padding:16px}.story-label{font-size:9px;font-weight:900;letter-spacing:.12em;color:var(--muted)}.story-box h4{margin:6px 0 4px;font-size:18px}.story-box p{margin:0;color:#5f584f;line-height:1.45;font-size:12px}.story-controls{display:flex;gap:7px;margin-top:12px}.story-controls button,.daily-box button{min-height:38px;border:1px solid var(--line);border-radius:10px;padding:8px 11px;background:#fff;font-weight:900}.story-controls button.primary-mini,.daily-box button.primary-mini{background:#191919;color:#fff;border-color:#191919}.daily-box h4{margin:6px 0 4px;font-size:17px}.daily-box p{margin:0;color:var(--muted);font-size:11px;line-height:1.4}.daily-progress{height:7px;border-radius:99px;background:#eee8dc;margin:12px 0 9px;overflow:hidden}.daily-progress i{display:block;height:100%;width:0;background:var(--accent);border-radius:inherit;transition:width .4s ease}.daily-state{font-size:10px;font-weight:900}.living-note{margin-top:11px;color:var(--muted);font-size:10px;line-height:1.45}.pause-motion{margin-left:auto}.motion-toggle{font-size:10px!important;background:#f4eee2!important}
    @keyframes parkRunA{0%,100%{transform:translate(0,0) rotate(-4deg)}25%{transform:translate(115px,-20px) rotate(5deg)}55%{transform:translate(230px,8px) rotate(-3deg)}80%{transform:translate(80px,4px) rotate(4deg)}}
    @keyframes parkRunB{0%,100%{transform:translate(0,0) rotate(3deg)}30%{transform:translate(-120px,-15px) rotate(-5deg)}60%{transform:translate(90px,-28px) rotate(5deg)}85%{transform:translate(180px,4px) rotate(-3deg)}}
    @keyframes parkRunC{0%,100%{transform:translate(0,0) rotate(-2deg)}35%{transform:translate(-150px,7px) rotate(4deg)}70%{transform:translate(-35px,-24px) rotate(-4deg)}}
    @keyframes parkRunD{0%,100%{transform:translate(0,0) rotate(2deg)}35%{transform:translate(170px,-15px) rotate(-4deg)}65%{transform:translate(255px,3px) rotate(4deg)}85%{transform:translate(65px,-7px) rotate(-2deg)}}
    @keyframes parkRunE{0%,100%{transform:translate(0,0) rotate(2deg)}40%{transform:translate(-175px,-30px) rotate(-5deg)}75%{transform:translate(-250px,2px) rotate(4deg)}}
    @keyframes dogPlay{0%,100%{transform:translateY(0) rotate(0) scale(1)}35%{transform:translateY(-24px) rotate(-8deg) scale(1.12)}65%{transform:translateY(-10px) rotate(8deg) scale(1.06)}}
    @keyframes ballFly{0%{opacity:1;transform:translate(0,0) scale(.7)}100%{opacity:0;transform:translate(115px,-75px) scale(1.15)}}
    @keyframes heartPop{0%{opacity:0;transform:translateY(0) scale(.5)}20%{opacity:1}100%{opacity:0;transform:translateY(-65px) scale(1.3)}}
    @media(max-width:720px){.living-head{flex-direction:column}.park-stage{height:285px}.park-dog{font-size:34px}.living-bottom{grid-template-columns:1fr}.park-water{right:18%;width:110px}.park-tree{font-size:38px}.pause-motion{margin-left:0}}
    @media(prefers-reduced-motion:reduce){.park-dog,.park-ball,.park-heart,.live-pill i{animation:none!important}.park-dog{transform:none!important}.daily-progress i{transition:none}}
    .motion-off .park-dog,.motion-off .park-ball,.motion-off .park-heart{animation:none!important}.motion-off .park-dog{transform:none!important}
  `;
  document.head.appendChild(style);

  const card = document.createElement('section');
  card.id = 'livingDogPark'; card.className = 'living-card';
  card.innerHTML = `
    <div class="living-head"><div><span class="tag">BARK PARK · LIVE WORLD</span><h3>Don't just read about the dog internet. Watch it live.</h3><p>Dogs wander, chase balls, meet friends and create tiny stories even when you do nothing. Your dog is one character in a larger, playful world.</p></div><div class="live-pill"><i></i> PARK IS ALIVE</div></div>
    <div class="park-stage" id="parkStage" role="img" aria-label="Animated dog park where dogs play and meet"><div class="park-sun">☀️</div><div class="park-tree t1">🌳</div><div class="park-tree t2">🌳</div><div class="park-path"></div><div class="park-water"></div><div class="park-dog d1" tabindex="0" data-dog="Milo">🐕<small>Milo · fetch expert</small></div><div class="park-dog d2" tabindex="0" data-dog="Luna">🐺<small>Luna · zoomie captain</small></div><div class="park-dog d3" tabindex="0" data-dog="Biscuit">🐶<small>Biscuit · biscuit scientist</small></div><div class="park-dog d4" tabindex="0" data-dog="Pepper">🐩<small>Pepper · park mayor</small></div><div class="park-dog d5" tabindex="0" data-dog="Coco">🦮<small>Coco · friendly guide</small></div><div class="park-ball" id="parkBall">🎾</div><div class="park-heart" id="parkHeart">💛</div></div>
    <div class="living-bottom"><article class="story-box"><div class="story-label">LIVE STORY · EPISODE <span id="storyEpisode">01</span></div><h4 id="storyTitle">The Ball Nobody Could Catch</h4><p id="storyText">Milo dropped the tennis ball. Luna saw it. Biscuit saw Luna see it. Within seconds, the entire park had a mission.</p><div class="story-controls"><button type="button" id="storyNext" class="primary-mini">Next scene →</button><button type="button" id="storyPlay">▶ Auto story</button><button type="button" id="motionToggle" class="motion-toggle">Pause motion</button></div></article><article class="daily-box"><div class="story-label">TODAY'S PAWPRINT</div><h4 id="dailyTitle">Say hello to the park</h4><p id="dailyText">Tap any dog or watch one playful scene.</p><div class="daily-progress"><i id="dailyBar"></i></div><div class="daily-state" id="dailyState">0 / 1 complete</div><button type="button" id="dailyClaim" class="primary-mini" disabled>Complete today's moment</button></article></div>
    <p class="living-note">Designed for short, gentle play: no countdown pressure, no punishment for missing a day, and motion can be paused at any time. The world can be enjoyed by touch, mouse or keyboard.</p>`;
  const observatory = document.querySelector('#observatory');
  if (observatory) world.insertBefore(card, observatory); else world.appendChild(card);

  const park = card.querySelector('#parkStage');
  const dogs = [...card.querySelectorAll('.park-dog')];
  const stories = [
    ['The Ball Nobody Could Catch','Milo dropped the tennis ball. Luna saw it. Biscuit saw Luna see it. Within seconds, the entire park had a mission.'],
    ['A Very Serious Sniff','Pepper discovered a mysterious smell beside the water. Coco joined the investigation. The conclusion: probably a leaf.'],
    ['The Friendship Sprint','Luna invited Biscuit to race to the big tree. Biscuit had no idea what the rules were, so everyone won.'],
    ['Treat Diplomacy','Coco offered a pretend biscuit. Milo offered a pretend second biscuit. Peace was declared across the park.'],
    ['Sunset Zoomies','The sun started getting lower. Nobody wanted to go home yet, so the dogs invented one final lap around the park.'],
    ['The Quiet Bench','After all that running, the dogs sat together. Sometimes the best adventure is simply being near a friend.']
  ];
  let storyIndex = 0; let storyTimer = null; let motionOff = reduced;
  const storyTitle = card.querySelector('#storyTitle'); const storyText = card.querySelector('#storyText'); const episode = card.querySelector('#storyEpisode');
  const renderStory = () => { const [title,text] = stories[storyIndex % stories.length]; episode.textContent = String((storyIndex % stories.length)+1).padStart(2,'0'); storyTitle.textContent = title; storyText.textContent = text; dogs.forEach((d) => d.classList.remove('playing')); const a = dogs[storyIndex % dogs.length]; const b = dogs[(storyIndex+1) % dogs.length]; a.classList.add('playing'); b.classList.add('playing'); spawn('parkBall','🎾',a); spawn('parkHeart','💛',b); dailyDone(); };
  const spawn = (id, icon, dog) => { const el = card.querySelector(`#${id}`); if (!el || !dog) return; const r = dog.getBoundingClientRect(); const p = park.getBoundingClientRect(); el.textContent = icon; el.style.left = `${Math.max(5, Math.min(90, ((r.left-p.left)/p.width)*100))}%`; el.style.top = `${Math.max(20, Math.min(80, ((r.top-p.top)/p.height)*100))}%`; el.classList.remove('fly','pop'); void el.offsetWidth; el.classList.add(id === 'parkBall' ? 'fly' : 'pop'); };
  const dailyDone = () => { const d = read(); if (d.day !== dayKey()) { d.day = dayKey(); d.done = false; save(d); } if (!d.done) { d.done = true; save(d); } card.querySelector('#dailyBar').style.width = '100%'; card.querySelector('#dailyState').textContent = '1 / 1 complete · Pawprint collected'; card.querySelector('#dailyClaim').disabled = false; card.querySelector('#dailyClaim').textContent = '✓ Pawprint collected'; };
  const next = () => { storyIndex = (storyIndex + 1) % stories.length; renderStory(); };
  card.querySelector('#storyNext').addEventListener('click', next);
  card.querySelector('#storyPlay').addEventListener('click', (e) => { if (storyTimer) { clearInterval(storyTimer); storyTimer = null; e.currentTarget.textContent = '▶ Auto story'; } else { storyTimer = setInterval(next, 7000); e.currentTarget.textContent = 'Ⅱ Pause story'; } });
  card.querySelector('#motionToggle').addEventListener('click', (e) => { motionOff = !motionOff; card.classList.toggle('motion-off', motionOff); e.currentTarget.textContent = motionOff ? 'Play motion' : 'Pause motion'; });
  card.querySelector('#dailyClaim').addEventListener('click', () => { dailyDone(); storyTitle.textContent = 'Today's Pawprint is safe'; storyText.textContent = 'Come back whenever you want. Tomorrow the park gets a new little moment.'; });
  dogs.forEach((dog) => { const interact = () => { dailyDone(); dogs.forEach((d) => d.classList.remove('playing')); dog.classList.add('playing'); const idx = dogs.indexOf(dog); const buddy = dogs[(idx + 1) % dogs.length]; buddy.classList.add('playing'); spawn('parkBall','🎾',dog); spawn('parkHeart','💛',buddy); storyTitle.textContent = `${dog.dataset.dog} met a new friend`; storyText.textContent = `${dog.dataset.dog} trotted over to ${buddy.dataset.dog}. A tail wag, a tiny sprint and a shared tennis ball later, the park had a new friendship.`; }; dog.addEventListener('click', interact); dog.addEventListener('keydown', (e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); interact(); } }); });
  renderStory();
  if (!reduced) storyTimer = setInterval(next, 9000);
  const d = read(); if (d.day === dayKey() && d.done) dailyDone();
  window.BARKVERSE_LIVING_WORLD = { nextStory: next, pause: () => { motionOff = true; card.classList.add('motion-off'); } };
})();
