const GOOGLE_MODEL = process.env.GOOGLE_AI_MODEL || 'gemini-2.5-flash';
const OPENROUTER_MODEL = 'openrouter/free';
const OPENROUTER_VISION_MODEL = 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free';
const AI_TIMEOUT_MS = 20000;
function jsonResponse(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(payload));}
function extractText(payload){return payload?.candidates?.[0]?.content?.parts?.map(p=>p?.text||'').join('').trim()||'';}
function extractOpenRouterText(payload){return payload?.choices?.[0]?.message?.content?.trim?.()||'';}
function parseJsonText(text){if(!text)return null;try{return JSON.parse(text)}catch{}const fenced=text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i);if(fenced)try{return JSON.parse(fenced[1])}catch{}const object=text.match(/\{[\s\S]*\}/);if(object)try{return JSON.parse(object[0])}catch{}return null;}
function timeoutSignal(ms=AI_TIMEOUT_MS){if(typeof AbortSignal?.timeout==='function')return AbortSignal.timeout(ms);const controller=new AbortController();setTimeout(()=>controller.abort(),ms);return controller.signal;}
async function callGoogle({prompt,image,audio}){const key=process.env.GOOGLE_AI_API_KEY;if(!key)throw new Error('GOOGLE_AI_API_KEY is not configured');const contents=[];if(image?.data)contents.push({inlineData:{mimeType:image.mimeType||'image/jpeg',data:image.data}});if(audio?.data)contents.push({inlineData:{mimeType:audio.mimeType||'audio/webm',data:audio.data}});contents.push({text:prompt});const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${GOOGLE_MODEL}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents,generationConfig:{temperature:0.9,responseMimeType:'application/json'}}),signal:timeoutSignal()});if(!response.ok)throw new Error(`Google AI ${response.status}`);const text=extractText(await response.json());if(!text)throw new Error('Google AI returned no text');return{text,provider:'google-ai'};}
async function callOpenRouter({prompt,image,model=OPENROUTER_MODEL}){const key=process.env.OPENROUTER_API_KEY;if(!key)throw new Error('OPENROUTER_API_KEY is not configured');const content=[{type:'text',text:prompt}];if(image?.data)content.push({type:'image_url',image_url:{url:`data:${image.mimeType||'image/jpeg'};base64,${image.data}`}});const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`,'HTTP-Referer':process.env.APP_URL||'https://barkverse.vercel.app','X-Title':'BARKVERSE'},body:JSON.stringify({model,messages:[{role:'user',content}],temperature:0.6,max_tokens:1800}),signal:timeoutSignal()});if(!response.ok){let detail='';try{const body=await response.json();detail=body?.error?.message||''}catch{}throw new Error(`OpenRouter ${response.status}${detail?`: ${detail}`:''}`);}const text=extractOpenRouterText(await response.json());if(!text)throw new Error('OpenRouter returned no text');return{text,provider:model};}
async function generate({prompt,image,audio}){const errors=[];
  // Prefer Google when configured. It is the strongest general vision path.
  if(process.env.GOOGLE_AI_API_KEY){try{return await callGoogle({prompt,image,audio})}catch(error){errors.push(error?.name==='TimeoutError'||error?.name==='AbortError'?'Google AI timed out':error.message)}}
  // For image requests, use a known free multimodal OpenRouter model explicitly. This avoids
  // depending on the free router selecting a vision endpoint correctly under changing pool capacity.
  if(!audio && image?.data && process.env.OPENROUTER_API_KEY){try{return await callOpenRouter({prompt,image,model:OPENROUTER_VISION_MODEL})}catch(error){errors.push(error?.name==='TimeoutError'||error?.name==='AbortError'?'OpenRouter vision timed out':error.message)}}
  if(!audio && process.env.OPENROUTER_API_KEY){try{return await callOpenRouter({prompt,image,model:OPENROUTER_MODEL})}catch(error){errors.push(error?.name==='TimeoutError'||error?.name==='AbortError'?'OpenRouter timed out':error.message)}}
  throw new Error(errors.join(' | ') || 'No AI provider is configured');
}
module.exports={generate,parseJsonText,jsonResponse};
