-- BARKVERSE Snowflake analytics schema
-- Stores only anonymous session/event telemetry and numeric dog-world traits.
CREATE TABLE IF NOT EXISTS BARK_EVENTS (
  EVENT_ID STRING,
  SESSION_ID STRING,
  EVENT_TYPE STRING,
  CHAOS NUMBER(3,0),
  ZOOMIES NUMBER(3,0),
  LOYALTY NUMBER(3,0),
  CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW BARK_OBSERVATORY AS
SELECT
  COUNT(*) AS EVENTS,
  COUNT(DISTINCT SESSION_ID) AS SESSIONS,
  ROUND(AVG(ZOOMIES), 0) AS AVG_ZOOMIES,
  ROUND(AVG(CHAOS), 0) AS AVG_CHAOS,
  ROUND(AVG(LOYALTY), 0) AS AVG_LOYALTY
FROM BARK_EVENTS;
